Repository ChwitKey/ChwitKey-Android, pull requests merged in 2023-08, with the labels that each got.

#47 [Feat] 25 - search news layout
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/NewsRecyclerViewAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/RecyclerViewAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/SearchRecordAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/home/HomeActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/home/News.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/home/homeNews/HomeNewsFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/newsSearch/NewsSearchActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/newsSearch/SearchRecord.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/searchList/SearchListActivity.kt
  app/src/main/res/color/bottom_nav_home_selector.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_keyword.xml
  app/src/main/res/drawable/ic_keyword_true.xml
  app/src/main/res/drawable/ic_my_page.xml
  app/src/main/res/drawable/ic_my_page_true.xml
  app/src/main/res/drawable/ic_nav_background.xml
  app/src/main/res/drawable/ic_nav_background2.xml
  app/src/main/res/drawable/ic_scrap.xml
  app/src/main/res/drawable/ic_scrap_true.xml
  app/src/main/res/drawable/nav_shadow.xml
  app/src/main/res/layout/activity_gpt.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_news_search.xml
  app/src/main/res/layout/activity_search_list.xml
  app/src/main/res/layout/fragment_home_news.xml
  app/src/main/res/layout/fragment_search_keyword.xml
  app/src/main/res/layout/item_keyword_btn.xml
  app/src/main/res/layout/item_news.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/menu/menu_bottom_nav_home.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 푸, feature

#57 Feature/52 scrap layout
  app/build.gradle
  app/src/main/java/com/example/cherry_pick_android/data/data/News.kt
  app/src/main/java/com/example/cherry_pick_android/domain/model/SearchRecord.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/NewsRecyclerViewAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/ScrapAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/SearchRecordAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/article/ArticleActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/newsSearch/NewsSearchActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/newsSearch/SearchRecord.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/scrap/ScrapTrueFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/searchList/SearchListActivity.kt
  app/src/main/res/layout/activity_article.xml
  app/src/main/res/layout/activity_news_search.xml
  app/src/main/res/layout/item_news.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/values/strings.xml
Labels: 푸, layout, feature

#56 [Feature] 로그인 레이아웃, 생년월일 레이아웃 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/infrom/InformSettingActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/infrom/dialog/GenderDialog.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/infrom/dialog/GenderDialogInterface.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/login/LoginActivity.kt
  app/src/main/res/drawable/ic_login_kakao.png
  app/src/main/res/drawable/ic_login_kakao_bg.xml
  app/src/main/res/drawable/ic_login_naver.png
  app/src/main/res/drawable/ic_login_naver_bg.xml
  app/src/main/res/drawable/ic_setting_check.xml
  app/src/main/res/drawable/ic_setting_complete.xml
  app/src/main/res/drawable/ic_setting_error.xml
  app/src/main/res/drawable/ic_setting_gender.xml
  app/src/main/res/drawable/ic_setting_gender_divide.xml
  app/src/main/res/drawable/ic_setting_line.xml
  app/src/main/res/drawable/ic_setting_no_complete.xml
  app/src/main/res/layout/activity_inform_setting.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/dialog_gender.xml
  app/src/main/res/layout/fragment_first_keyword.xml
  app/src/main/res/layout/fragment_keyword.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 준, layout

#59 [Refactor] Dialog 조정, 레이아웃 수정, 폰트적용
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/keyword/dialog/KeywordDialog.kt
  app/src/main/res/layout/fragment_search_keyword.xml
Labels: 준, layout

#65 Feature/38 profile job group
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/cherry_pick_android/domain/model/JobGroup.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/JobGroupAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/jobGroup/JobGroupActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/jobGroup/JobGroups.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/ProfileActivity.kt
  app/src/main/res/drawable/ic_job_button.xml
  app/src/main/res/drawable/ic_job_button_clicked.xml
  app/src/main/res/drawable/ic_job_complete.xml
  app/src/main/res/drawable/ic_job_complete_clicked.xml
  app/src/main/res/drawable/ic_mypage_menu.xml
  app/src/main/res/drawable/ic_mypage_to_profile.xml
  app/src/main/res/drawable/ic_mypage_user.xml
  app/src/main/res/drawable/ic_pencil.xml
  app/src/main/res/drawable/ic_pencil_complete.xml
  app/src/main/res/drawable/icon_change_job.png
  app/src/main/res/drawable/icon_keyword_setting.png
  app/src/main/res/drawable/icon_profile_leave_account.png
  app/src/main/res/drawable/icon_profile_logout.png
  app/src/main/res/drawable/icon_saved_article.png
  app/src/main/res/layout/activity_job_group.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/item_job_group.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 연두, layout, feature

#69 [Feat] 카카오 SDK 로그인 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/login/loginManager/KakaoLoginManager.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/util/ApplicationClass.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/viewmodel/login/LoginViewModel.kt
  gradle.properties
  settings.gradle
Labels: 준, SDK

#73 [Feat] : GridViewItem 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/JobGroupAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/jobGroup/JobGroupActivity.kt
  app/src/main/res/drawable/ic_job_button.xml
  app/src/main/res/drawable/ic_job_button_clicked.xml
  app/src/main/res/layout/activity_job_group.xml
  app/src/main/res/layout/item_job_group.xml
Labels: 연두, layout

#77 [Fix] : 직군 버튼 수정
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/JobGroupAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/jobGroup/JobGroupActivity.kt
  app/src/main/res/layout/activity_job_group.xml
Labels: 연두, layout

#78 [Feat] 자동로그인 구현
  app/build.gradle
  app/src/main/java/com/example/cherry_pick_android/data/module/api/ApiModule.kt
  app/src/main/java/com/example/cherry_pick_android/data/module/datastore/DataStoreModule.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/repository/UserIdRepositoryImpl.kt
  app/src/main/java/com/example/cherry_pick_android/domain/model/UserId.kt
  app/src/main/java/com/example/cherry_pick_android/domain/repository/UserIdRepository.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/viewmodel/login/LoginViewModel.kt
Labels: 준, feature

#75 Feature/72 room search
  app/src/main/java/com/example/cherry_pick_android/data/db/RecordDAO.kt
  app/src/main/java/com/example/cherry_pick_android/data/db/RecordDB.kt
  app/src/main/java/com/example/cherry_pick_android/data/mapper/RecordMapper.kt
  app/src/main/java/com/example/cherry_pick_android/data/model/SearchRecordEntity.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/repository/RecordRepositoryImpl.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/ArticleDetailService.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/ArticleUnlikeService.kt
  app/src/main/java/com/example/cherry_pick_android/domain/repository/RecordRepository.kt
  app/src/main/java/com/example/cherry_pick_android/domain/usecase/AddRecordUseCase.kt
  app/src/main/java/com/example/cherry_pick_android/domain/usecase/DeleteRecordUseCase.kt
  app/src/main/java/com/example/cherry_pick_android/domain/usecase/ReadRecordUseCase.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/ArticleKeywordAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/SearchRecordAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/di/LocalDataModule.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/di/RepositoryModule.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/home/HomeActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/keyword/search/SearchKeywordFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/newsSearch/ArticleSearchFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/newsSearch/NewsSearchActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/newsSearch/SearchListFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/scrap/ScrapNoneFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/searchList/SearchListActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/viewmodel/searchRecord/SearchRecordViewModel.kt
  app/src/main/res/layout/activity_news_search.xml
  app/src/main/res/layout/fragment_article_search.xml
  app/src/main/res/layout/fragment_home_news.xml
  app/src/main/res/layout/fragment_search_list.xml
Labels: 푸, feature

#82 [Fix] : 취소 기능 수정
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/JobGroupAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/jobGroup/JobGroupActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/ProfileActivity.kt
  app/src/main/res/drawable/ic_my_page_logout.xml
  app/src/main/res/drawable/ic_my_page_menu.xml
  app/src/main/res/drawable/ic_my_page_setting.xml
  app/src/main/res/drawable/ic_my_page_user.xml
  app/src/main/res/layout/activity_job_group.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/item_job_group.xml
  app/src/main/res/values/strings.xml
Labels: 연두, layout

#85 [Feat] : 카메라 다이얼로그 임시 추가
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/dialog/CameraDialog.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/dialog/CameraDialogInterface.kt
  app/src/main/res/drawable/bg_camera_dialog.xml
  app/src/main/res/drawable/ic_camera_dialog_text.xml
  app/src/main/res/layout/dialog_camera.xml
Labels: 연두, layout

#83 [Fix] 직군 완료 버튼 로직 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/cherry_pick_android/data/remote/repository/UserDataRepositoryImpl.kt
  app/src/main/java/com/example/cherry_pick_android/domain/repository/UserDataRepository.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/jobGroup/JobGroupActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/viewmodel/login/LoginViewModel.kt
Labels: 준

#86 [Feat] 정렬 선택 및 최근 검색어 최종 구현
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/java/com/example/cherry_pick_android/data/module/api/ApiModule.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/repository/ArticleRepository.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/ArticleCommendResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/ArticleSearchService.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/ArticleAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/ArticleKeywordAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/SearchRecordAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/home/homeNews/HomeNewsFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/newsSearch/ArticleSearchFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/newsSearch/NewsSearchActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/newsSearch/SearchListFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/viewmodel/article/ArticleViewModel.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/viewmodel/home/HomeNewsViewModel.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/viewmodel/keyword/SearchKeywordViewModel.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/viewmodel/searchRecord/SearchRecordViewModel.kt
  app/src/main/res/menu/menu_article_sort.xml
  app/src/main/res/values/strings.xml
Labels: 푸, layout, feature

#87 [Refactor] 직군 어뎁터 코드 가독성 증가를 위한 리팩토링
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/JobGroupAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/ProfileActivity.kt
Labels: 준, refactor

#89 [Feat] : 프로필 사진 카메라 연동
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/ProfileActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/dialog/CameraDialog.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/dialog/CameraDialogInterface.kt
  app/src/main/res/drawable/bg_camera_dialog.xml
Labels: 연두, layout, feature

#94 [Feat] 로그아웃 및 회원탈퇴기능 구현
  app/src/main/java/com/example/cherry_pick_android/data/module/api/ApiModule.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/user/DeleteUserResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/user/DeleteUserService.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/ProfileActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/dialog/UserDeleteDialog.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/dialog/UserDeleteDialogInterface.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/viewmodel/login/LoginViewModel.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/viewmodel/mypage/MyPageViewModel.kt
  app/src/main/res/drawable/bg_user_delete_dialog.xml
  app/src/main/res/drawable/ic_user_delete_logo.xml
  app/src/main/res/layout/dialog_delete_user.xml
  app/src/main/res/values/strings.xml
Labels: 준

#97 [Feat] 유저 닉네임 변경 업데이트 및 토큰갱신
  app/src/main/java/com/example/cherry_pick_android/data/module/api/ApiModule.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/repository/UserDataRepositoryImpl.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/request/user/updateNameRequest.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/user/DeleteUserResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/user/DeleteUserService.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/user/UserNameUpdateService.kt
  app/src/main/java/com/example/cherry_pick_android/domain/repository/UserDataRepository.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/ProfileActivity.kt
Labels: 준

#102 [Feat] 직군업데이트 및 회원정보 갱신
  app/src/main/java/com/example/cherry_pick_android/data/module/api/ApiModule.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/request/user/updateIndustryRequest.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/user/ApiResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/user/UpdateIndustryResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/user/UserInfoResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/user/UpdateIndustryService.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/jobGroup/JobGroupActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/ProfileActivity.kt
Labels: 준

#103 Feature/95 article api
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/cherry_pick_android/data/data/Pageable.kt
  app/src/main/java/com/example/cherry_pick_android/data/module/api/ApiModule.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/repository/ArticleRepository.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleCommendResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleDetailResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleIndustryResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleKeywordResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleLikeResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleNewResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleUnlikeResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/ArticleSearchService.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/article/ArticleDetailService.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/article/ArticleLikeService.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/article/ArticleNewService.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/article/ArticleSearchCommendService.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/article/ArticleSearchIndustryService.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/article/ArticleSearchKeywordService.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/article/ArticleUnlikeService.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/ArticleAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/NewsRecyclerViewAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/home/homeNews/HomeNewsFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/newsSearch/SearchListFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/viewmodel/article/ArticleViewModel.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/viewmodel/home/HomeNewsViewModel.kt
  app/src/main/res/layout/item_news.xml
  app/src/main/res/layout/item_scrap_news.xml
Labels: 푸, feature, API

#105 [Feat] 유저 생년월일, 성별 갱신
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/ProfileActivity.kt
Labels: 준

#113 [Feat] 기사 상세 조회 API 연결
  .idea/deploymentTargetDropDown.xml
  .idea/vcs.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleCommendResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleDetailResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/user/UserInfoResponse.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/ArticleAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/IndustryAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/article/ArticleActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/home/homeNews/HomeNewsFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/newsSearch/ArticleSearchFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/newsSearch/NewsSearchActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/newsSearch/SearchListFragment.kt
  app/src/main/res/drawable/bg_keyword_false.xml
  app/src/main/res/layout/activity_article.xml
  app/src/main/res/layout/activity_news_search.xml
  app/src/main/res/layout/fragment_home_news.xml
  app/src/main/res/layout/item_scrap_news.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 푸, feature, API

#117 [Feat] 스크랩 구현
  app/src/main/java/com/example/cherry_pick_android/data/module/api/ApiModule.kt
  app/src/main/java/com/example/cherry_pick_android/data/module/api/AppInterceptor.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/request/ArticleLikeDTO.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleLikeResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleUnlikeResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/article/ArticleLikeService.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/article/ArticleUnlikeService.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/article/ArticleActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/util/ApplicationClass.kt
  app/src/main/res/values/strings.xml
Labels: 준, API

#119 [Refactor] 공유하기 uri추가 및 스플레시 화면 틀 구축
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleLikeResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleUnlikeResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/article/ArticleLikeService.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/article/ArticleActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/ProfileActivity.kt
  app/src/main/res/drawable/splash_logo.xml
  app/src/main/res/drawable/splash_text.xml
  app/src/main/res/values/themes.xml
Labels: 준

#122 [Refactor] 앱 최적화
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/infrom/InformSettingActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/jobGroup/JobGroupActivity.kt
  app/src/main/res/drawable/bg_active_btn.xml
  app/src/main/res/drawable/bg_disabled_btn.xml
  app/src/main/res/drawable/bg_gray1.xml
  app/src/main/res/drawable/bg_scrap_toolbar.xml
  app/src/main/res/drawable/bg_scrap_toolbar_png.png
  app/src/main/res/drawable/ic_gpt_back.xml
  app/src/main/res/drawable/ic_gpt_et.xml
  app/src/main/res/drawable/ic_home_search_news_background.png
  app/src/main/res/drawable/ic_iskeyword_search.xml
  app/src/main/res/drawable/ic_job_complete.xml
  app/src/main/res/drawable/ic_job_complete_clicked.xml
  app/src/main/res/drawable/ic_keyword_btn.xml
  app/src/main/res/drawable/ic_keyword_complete.xml
  app/src/main/res/drawable/ic_keyword_et.xml
  app/src/main/res/drawable/ic_keyword_search_background.xml
  app/src/main/res/drawable/ic_right_btn.xml
  app/src/main/res/drawable/ic_right_snack_bar.xml
  app/src/main/res/drawable/ic_setting_complete.xml
  app/src/main/res/drawable/ic_setting_gender.xml
  app/src/main/res/drawable/ic_setting_no_complete.xml
  app/src/main/res/layout/activity_gpt.xml
  app/src/main/res/layout/activity_inform_setting.xml
  app/src/main/res/layout/activity_job_group.xml
  app/src/main/res/layout/activity_news_search.xml
  app/src/main/res/layout/dialog_gender.xml
  app/src/main/res/layout/fragment_home_news.xml
  app/src/main/res/layout/fragment_keyword.xml
  app/src/main/res/layout/fragment_scrap_none.xml
  app/src/main/res/layout/fragment_scrap_true.xml
  app/src/main/res/layout/fragment_search_keyword.xml
Labels: 준

#123 [Feat] 기사 직군별 요청
  app/src/main/java/com/example/cherry_pick_android/data/data/ArticleItem.kt
  app/src/main/java/com/example/cherry_pick_android/data/module/api/ApiModule.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleIndustryResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/article/ArticleSearchIndustryService.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/IndustryAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/KeywordListAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/adapter/NewsRecyclerViewAdapter.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/home/homeNews/HomeNewsFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/keyword/AdapterInteractionListener.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/keyword/KeywordFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/keyword/search/SearchKeywordDetailFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/newsSearch/SearchListFragment.kt
  app/src/main/res/layout/fragment_search_keyword.xml
  app/src/main/res/layout/fragment_search_keyword_detail.xml
  app/src/main/res/menu/menu_article_sort.xml
Labels: 푸, feature, API

#131 [Feat] : 로딩 바 추가 (#130)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/article/ArticleActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/home/homeNews/HomeNewsFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/keyword/KeywordFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/keyword/first/FirstKeywordFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/keyword/search/SearchKeywordDetailFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/keyword/search/SearchKeywordFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/newsSearch/ArticleSearchFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/newsSearch/NewsSearchActivity.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/newsSearch/SearchListFragment.kt
  app/src/main/res/layout/activity_article.xml
  app/src/main/res/layout/fragment_first_keyword.xml
  app/src/main/res/layout/fragment_keyword.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_scrap_true.xml
  app/src/main/res/layout/fragment_search_keyword_detail.xml
  app/src/main/res/layout/fragment_search_list.xml
  app/src/main/res/raw/lottie_dot_loading.json
Labels: 푸, layout, feature

#139 [Feat] 무한 스크롤 전체 적용
  app/src/main/java/com/example/cherry_pick_android/data/data/ArticleItem.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleNewResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/response/article/ArticleScrapResponse.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/article/ArticleNewService.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/article/ArticleSearchCommendService.kt
  app/src/main/java/com/example/cherry_pick_android/data/remote/service/article/ArticleSearchKeywordService.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/home/homeNews/HomeNewsFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/keyword/KeywordFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/keyword/search/SearchKeywordDetailFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/keyword/search/SearchKeywordFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/newsSearch/SearchListFragment.kt
  app/src/main/res/layout/fragment_home_news.xml
  app/src/main/res/layout/fragment_keyword.xml
  app/src/main/res/layout/fragment_scrap_true.xml
  app/src/main/res/layout/fragment_search_list.xml
  app/src/main/res/layout/item_gpt_loading.xml
  app/src/main/res/layout/item_keyword_btn.xml
  app/src/main/res/layout/item_keyword_complete_btn.xml
  app/src/main/res/layout/item_scrap_news.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 푸, layout, feature, API

#138 [Feat] : 이용약관 관련 페이지 구현
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/assets/임시개인정보처리방침.txt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/MarketingPolicy.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/PrivacyPolicy.kt
  app/src/main/java/com/example/cherry_pick_android/presentation/ui/mypage/UserPolicy.kt
  app/src/main/res/layout/activity_job_group.xml
  app/src/main/res/layout/activity_marketing_policy.xml
  app/src/main/res/layout/activity_privacy_policy.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_user_policy.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/values/strings.xml
Labels: 연두, layout, feature

#147 [Docs] ReadMe 작성
  README.md
Labels: 푸, Docs

#152 [Refactor] 회원탈퇴 연동해제 구현
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/chwitkey/cherry_pick_android/presentation/ui/login/loginManager/NaverLoginManager.kt
  app/src/main/java/com/chwitkey/cherry_pick_android/presentation/ui/mypage/ProfileActivity.kt
Labels: 준
